const stuff = require('./build/Release/OSX.node');

module.exports.U = stuff.U;
module.exports.UR = stuff.UR;
module.exports.UW = stuff.UW;
module.exports.UX = stuff.UX;
module.exports.G = stuff.G;
module.exports.GR = stuff.GR;
module.exports.GW = stuff.GW;
module.exports.GX = stuff.GX;
module.exports.O = stuff.O;
module.exports.OR = stuff.OR;
module.exports.OW = stuff.OW;
module.exports.OX = stuff.OX;
module.exports.SUID = stuff.SUID;
module.exports.GGID = stuff.GGID;
module.exports.STIK = stuff.STIK;
exports.Flock = stuff.Flock;
exports.SemaphoreP = stuff.SemaphoreP;
